name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Lint + Formatting
  check:
    name: Check & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Clippy (Linting)
        run: cargo clippy -- -D warnings

  # Normal Tests
  test:
    name: Test (Default)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --verbose

  # Stress GC Tests
  test-stress-gc:
    name: Test (Stress GC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run Tests with Stress GC
        run: cargo test --verbose --features stress_gc

  # Miri Safety Check
  miri:
    name: Miri Safety Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - uses: Swatinem/rust-cache@v2

      - name: Miri Test
        run: cargo miri test --lib src/vm/ --features stress_gc